require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/MissingSuper:
  Enabled: false

Lint/SuppressedException:
  AllowComments: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'
    - 'config/routes.rb'

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - spec/components/previews/**/*

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - spec/components/previews/**/*

Metrics/ParameterLists:
  Exclude:
    - app/components/**/*
    - spec/components/previews/**/*

Performance/BlockGivenWithExplicitBlock:
  Enabled: false

RSpec/ExampleLength:
  Max: 20
  CountAsOne: ['array', 'hash', 'heredoc']

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolProc:
  AllowMethodsWithArguments: true

Style/UnlessLogicalOperators:
  EnforcedStyle: forbid_logical_operators
